### ISSUE TITLE
Doesn't work on 1.17

### ISSUE THREAD

**Issue by Pooolg** [PacketClient/Packet-Client#2]
Doesn't work on 1.17

**Comment by PacketClient** [comment]
thats not an issue
the issue here is u being dumb

**Comment by PacketClient** [comment]
To update the client I would need to reverse engineer the games code, and I
have no clue how to do that.

**Comment by Pooolg** [comment]
> thats not an issue
> the issue here is u being dumb

Thank you, it was very nice. If I am not in depth on this topic, it does not mean that I am dumb.
